<?php
session_start();
include 'db.php';

$message = "";

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $name = mysqli_real_escape_string($conn, $_POST['name']);
    $class = mysqli_real_escape_string($conn, $_POST['class']);
    $password = mysqli_real_escape_string($conn, $_POST['password']);
    $gender = mysqli_real_escape_string($conn, $_POST['gender']);
    $phone = mysqli_real_escape_string($conn, $_POST['phone']);

    // --- 1. AUTOMATIC ROLL NUMBER LOGIC ---
    // Hum check kar rahe hain ke is class mein aakhri roll number kya tha
    $res = mysqli_query($conn, "SELECT MAX(CAST(roll_no AS UNSIGNED)) as last_roll FROM students WHERE class='$class'");
    $row = mysqli_fetch_assoc($res);
    
    // Agar bacha pehla hai toh 1, warna pichle mein +1
    $next_roll = ($row['last_roll'] > 0) ? $row['last_roll'] + 1 : 1;

    // --- 2. INSERT DATA ---
    $sql = "INSERT INTO students (name, class, roll_no, password, gender, phone, status) 
            VALUES ('$name', '$class', '$next_roll', '$password', '$gender', '$phone', 1)";

    if (mysqli_query($conn, $sql)) {
        $message = "<div class='alert success'>Student Registered! Roll No Assigned: <b>$next_roll</b></div>";
    } else {
        $message = "<div class='alert error'>Error: " . mysqli_error($conn) . "</div>";
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Student | School System</title>
    <style>
        body { font-family: 'Segoe UI', sans-serif; background: #f0f2f5; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
        .container { background: white; padding: 40px; border-radius: 15px; box-shadow: 0 10px 25px rgba(0,0,0,0.1); width: 450px; }
        h2 { text-align: center; color: #1a73e8; margin-bottom: 25px; }
        
        label { font-size: 14px; color: #555; font-weight: bold; }
        input, select { width: 100%; padding: 12px; margin: 8px 0 20px 0; border: 1px solid #ddd; border-radius: 8px; box-sizing: border-box; font-size: 15px; }
        
        button { width: 100%; padding: 14px; background: #1a73e8; color: white; border: none; border-radius: 8px; cursor: pointer; font-size: 16px; font-weight: bold; transition: 0.3s; }
        button:hover { background: #1557b0; }
        
        .alert { padding: 15px; border-radius: 8px; margin-bottom: 20px; text-align: center; }
        .success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .error { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        
        .info-text { font-size: 12px; color: #888; margin-top: -15px; margin-bottom: 15px; display: block; }
    </style>
</head>
<body>
    <div class="container">
        <h2>Add New Student</h2>
        
        <?php echo $message; ?>

        <form method="POST">
            <label>Full Name</label>
            <input type="text" name="name" placeholder="Enter student's full name" required>

            <label>Select Class</label>
            <select name="class" required>
                <option value="">-- Choose Class --</option>
                <option value="Nursery">Nursery</option>
                <option value="Prep">Prep</option>
                <option value="1st">1st</option>
                <option value="2nd">2nd</option>
                <option value="6th">6th</option>
                <option value="9th">9th</option>
                <option value="10th">10th</option>
            </select>

            <label>Roll Number</label>
            <input type="text" placeholder="Auto-generated by system" disabled style="background: #f9f9f9; cursor: not-allowed;">
            <span class="info-text">* System will automatically assign the next available roll number.</span>

            <label>Phone Number</label>
            <input type="text" name="phone" placeholder="Parent's contact number">

            <label>Gender</label>
            <select name="gender">
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Other">Other</option>
            </select>

            <label>Login Password</label>
            <input type="text" name="password" value="123456">

            <button type="submit">Add Student to Database</button>
        </form>
    </div>
</body>
</html>